### ISSUE TITLE
循环播放，刚衔接地方声音会变大。可以优化一下

### ISSUE THREAD

**Issue by zmh10241015** [DamonHu/HDCommonTools#1]

**Comment by DamonHu** [comment]
如果在AVPlayer的完成通知之后再播放第二个是不会有重复播放，之所以这么做，是因为如果等结束之后再去播放的话会因为加载的过程，造成短暂空白播放问题，所以会提前1s循环第二个部分。因为怕能耗问题，所以设置的1s监测CMTimeMake(1.0, 1.0)，修改成CMTimeMake(1.0, 1000.0)，然后提前时间减小即可。cocoapods已经提交了2.3.1版本，你可以尝试下

**Comment by DamonHu** [comment]
修改了循环播放的方式，不再联网循环播放，改成了缓存之后使用系统循环播放
